etoa/etoa-gui

eventhandler/src/entity/Entity.cpp
eventhandler/src/entity/Entity.h
eventhandler/src/fleet/fleetActions/SpyHandler.cpp

Fixed some error with disapearing ress. pls merge again to test.

Fixed problem that ress dissapered after raid.

---

htdocs/content/economy.php

gem. Zelos wird die Berechnung aufgrund der Basis * (planibonus + boost) berechnet und nicht basis * planibonus * boost

fixed boost display in economy

---

htdocs/content/economy.php

added missing key in economy.php which caused the total calculation to not be correct.
added hint text to total production to display production without boni

bugfix, added missing key in economy total calculation.

---

eventhandler/src/config/ConfigHandler.cpp

Fixes an sql error in newer mysql versions

Fix: max fuel value calculation

---

Changelog.md
htdocs/classes/gamestats.class.php

https://github.com/etoa/etoa-gui/issues/183

Ignore players in hmode for gamestats

---

.gitignore
db/migrations/0027-20200330-restore_civil_ships.sql
eventhandler/src/config/ConfigHandler.h
eventhandler/src/data/ShipData.cpp
eventhandler/src/data/ShipData.h
eventhandler/src/entity/Entity.cpp
eventhandler/src/entity/Entity.h
eventhandler/src/fleet/battle/BattleHandler.cpp
eventhandler/src/objects/FleetShip.cpp
eventhandler/src/objects/FleetShip.h
eventhandler/src/objects/ListDef.cpp
eventhandler/src/objects/ListDef.h
eventhandler/src/objects/ListShip.cpp
eventhandler/src/objects/ListShip.h
eventhandler/src/objects/Object.h
eventhandler/src/reports/BattleReport.cpp
eventhandler/src/reports/BattleReport.h
htdocs/classes/battlereport.class.php
htdocs/config/defaults.xml

Solves Rückerstattung ziviler Schiffe #106

Civil ship restore for defender

---

Changelog.md
htdocs/content/missiles.php

Resolves: https://github.com/etoa/etoa-gui/issues/203

Missile: allow sending more than 999 missiles at once

---

htdocs/content/bunker.php

Problem: Missing Abilities
Now:

Fix mouseover in bunker

---

htdocs/content/market.php
htdocs/content/market/own.php

Fix issue #145: Same return factor is displayed and used for calculations.

Adjust marketplace returnfactor (Issue #145)

---

data/quests.php

My first code contribution for EtoA :-)!
Mainly for testing the setup and creating a PR.

Fixed some texts in quests.php.

---

composer.json
composer.lock
htdocs/admin/content/overview.php
htdocs/admin/content/user/edit.inc.php
htdocs/admin/content/user/ipsearch.inc.php
htdocs/admin/content/user/observed.inc.php
htdocs/admin/content/user/sessions.inc.php
htdocs/admin/content/user/userlog.inc.php
htdocs/content/userconfig/logins.php

Added this as use of get_browser() usage was inconsistent and resulted in errors in some places as not always all keys were present.

Added reliable browser / OS detection

---

htdocs/admin/content/db/cleanup.inc.php
htdocs/admin/content/user/sessions.inc.php
htdocs/admin/index.php
htdocs/classes/adminsession.class.php
htdocs/classes/session.class.php
htdocs/classes/tasks/cleanupsessionlogstask.class.php
htdocs/classes/tasks/sessioncleanuptask.class.php
htdocs/classes/usersession.class.php
src/Admin/AdminSessionManager.php
src/User/UserRepository.php
src/User/UserServiceProvider.php
src/User/UserSessionManager.php
src/User/UserSessionRepository.php

Similar to what already exists for the AdminUser Session Manager. More refactoring needed in a future step, this is just the beginning.

Session manager refactoring

---

htdocs/admin/content/fleets.php
htdocs/classes/entity/planet.class.php
htdocs/classes/fleet.class.php
htdocs/classes/ownableentity.class.php
phpstan-baseline.neon
src/Fleet/Fleet.php
src/Fleet/FleetAction.php
src/Fleet/FleetRepository.php
src/Fleet/FleetSearchParameters.php
src/Fleet/FleetService.php
src/Fleet/FleetServiceProvider.php
src/Fleet/FleetShip.php
src/Fleet/FleetStatus.php
src/Fleet/InvalidFleetParametersException.php
src/UI/EntityCoordinatesSelector.php
src/UI/ShipSelector.php
src/UI/UIServiceProvider.php
src/UI/UserSelector.php
src/Universe/Entity/Entity.php
src/Universe/Entity/EntityCoordinates.php
src/Universe/Entity/EntityRepository.php
src/Universe/Entity/EntityService.php
src/Universe/Planet/PlanetRepository.php
src/Universe/UniverseServiceProvider.php

**Please merge after planet_resource_handling as its based on some changes there.**
Adapted the way planet and fleet resources are updated (in admin area for now). This can then be used as a basis to update the fleet launch code.

Planet fleet resource interaction

---

htdocs/designs/official/Rediscovery/design.xml
htdocs/designs/official/Rediscovery/discovery.css
htdocs/designs/official/Rediscovery/game.css
htdocs/designs/official/Rediscovery/inputs.css
htdocs/designs/official/Rediscovery/nav-main.css
htdocs/designs/official/Rediscovery/nav-mobile.css
htdocs/designs/official/Rediscovery/nav-top.css
htdocs/designs/official/Rediscovery/scripts.js
htdocs/designs/official/Rediscovery/style.css

Desktop now uses constant scaling. Improved some stylings. Fixed issues with the top and main navigation.

Fixed issues and improved scaling.

---

htdocs/config/defaults.xml
htdocs/content/crypto.php

https://forum.etoa.ch/index.php?page=Thread&postID=112859#post112859

Enhancements for crypto

---

eventhandler/src/config/ConfigHandler.cpp

Adjust spy level for support fleets to align with description in help.

---

htdocs/admin/content/galaxy/universe.php

Resolves https://github.com/etoa/etoa-gui/issues/429

Universe: fix galaxy layouts

---

src/Core/Twig/TwigExtension.php
src/HostCache/NetworkNameService.php

Resolves https://github.com/etoa/etoa-gui/issues/453

Network: fix access with null value

---

src/Security/Admin/AdminUserProvider.php

Resolves https://github.com/etoa/etoa-gui/issues/451

Admin: user provider should throw exception on refresh error

---

htdocs/classes/buildlistitem.class.php

test by creating new user and try to build Planetenbasis

fixed: new buildings don't start building

---

templates/components/admin_entity_search.html.twig

Fixes https://github.com/etoa/etoa-gui/issues/504

Admin: fix entities edit link

---

htdocs/admin/forms/races.php

Resolves https://github.com/etoa/etoa-gui/issues/508

Races: fix creation of new entry

---

.env
composer.json
composer.lock
config/packages/mailer.yaml
htdocs/config/defaults.xml
phpstan-baseline.neon
src/Support/Mail/MailSenderService.php
src/Support/Mail/MailServiceProvider.php
symfony.lock
tests/User/UserServiceTest.php

Replaces https://github.com/etoa/etoa-gui/pull/502 and fixes https://github.com/etoa/etoa-gui/issues/452

Mailer: add easier way to configure null transport

---

htdocs/content/defense.php
htdocs/content/research.php
htdocs/content/shipyard.php

wouldn't work if count to be set is equal to max avail people.

fixed off-by-one-error when setting people / worker count
